# Generated by Django 4.2.3 on 2023-09-18 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articulo',
            fields=[
                ('idarticulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Producto')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio venta')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='ingreso',
            fields=[
                ('idingreso', models.AutoField(primary_key=True, serialize=False)),
                ('proveedor', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='venta',
            fields=[
                ('idventa', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='lote',
            fields=[
                ('idlote', models.AutoField(primary_key=True, serialize=False)),
                ('lote', models.CharField(max_length=100, verbose_name='Lote')),
                ('cantidad_stock', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('idarticulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.articulo')),
            ],
        ),
        migrations.CreateModel(
            name='detalle_venta',
            fields=[
                ('iddetalle_venta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('idarticulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.articulo')),
                ('idventa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.venta')),
            ],
        ),
        migrations.CreateModel(
            name='detalle_ingreso',
            fields=[
                ('iddetalle_ingreso', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('idarticulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.articulo')),
                ('idingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ingreso')),
            ],
        ),
    ]
