# Generated by Django 4.2.3 on 2023-09-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_articulo_imagen_lote_precio_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='imagenes/'),
        ),
    ]
