# Generated by Django 4.2.3 on 2023-09-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_articulo_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_venta',
            name='precio',
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_hora',
            field=models.DateField(),
        ),
    ]
