# Generated by Django 4.2.3 on 2023-09-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_detalle_venta_precio_alter_venta_fecha_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='inventario/'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_hora',
            field=models.DateField(auto_now_add=True),
        ),
    ]
