# Generated by Django 4.2.3 on 2023-09-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_venta_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_venta',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
