# Generated by Django 4.2.3 on 2023-10-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_detalle_venta_cantidad_alter_venta_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=5),
        ),
        migrations.DeleteModel(
            name='detalle_ingreso',
        ),
        migrations.DeleteModel(
            name='ingreso',
        ),
    ]
