# Generated by Django 4.2.6 on 2023-10-22 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_alter_venta_total_delete_detalle_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio de venta'),
        ),
        migrations.AlterField(
            model_name='detalle_venta',
            name='idarticulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.articulo', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='detalle_venta',
            name='idventa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.venta', verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='cantidad_stock',
            field=models.IntegerField(verbose_name='Cantidad en stock'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='fecha_vencimiento',
            field=models.DateField(verbose_name='Fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='idarticulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.articulo', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio de compra'),
        ),
    ]
