# Generated by Django 4.2.3 on 2023-10-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_articulo_precio_venta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.FloatField(default='0.00'),
        ),
    ]
