# Generated by Django 4.2.3 on 2023-10-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_alter_venta_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha_hora',
            field=models.DateField(),
        ),
    ]
