# Generated by Django 4.2.3 on 2023-10-29 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_alter_venta_fecha_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_venta',
            name='idventa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.venta'),
        ),
    ]
