# Generated by Django 4.2.3 on 2023-10-29 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_alter_detalle_venta_idventa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='total',
        ),
    ]
